### ISSUE TITLE
When is MAM in develop implemented

### ISSUE THREAD

**Issue by Batzi1337** [Felandil/tangle-.net#68]
Hi, I've seen MAM implementation in master. But missing it in develop. Is there a reason for it? I'm using this library for a private project. Now I need the MAM implementation.

**Comment by Felandil** [comment]
Hey,

unfortunately, since the IOTA Chrysalis upgrade, MAM is deprecated and will be replaced with IOTA streams (https://github.com/iotaledger/streams). That means, that there no longer will be MAM support from my side (and also the MAM implementation does not work with the new main net).

I will, however, see if IOTA streams can be ported to C#, once it is in a finalized state.
